import ThemeProvider from '@/components/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import type { Metadata } from 'next'
import { allFonts } from './fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // suppressHydrationWarning: https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app
    <html lang="en" suppressHydrationWarning>
      <body className={`${allFonts.map((font) => font.variable).join(' ')} antialiased`}>
        <ThemeProvider>
          <main>{children}</main>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  )
}
