name: Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    # https://github.com/orgs/community/discussions/26940
    # https://github.com/zopefoundation/meta/issues/145
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm lint

  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    # https://github.com/orgs/community/discussions/26940
    # https://github.com/zopefoundation/meta/issues/145
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test:vitest

  playwright:
    name: Playwright
    runs-on: ubuntu-latest
    # https://github.com/orgs/community/discussions/26940
    # https://github.com/zopefoundation/meta/issues/145
    if: github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name !=
      github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test Build
        run: pnpm test:playwright:web-server:build
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
      - name: Install Playwright Browsers
        run: pnpm -F jsrepl exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm -F jsrepl test:playwright
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
